name: Deploy Laravel App via SFTP

on:
  push:
    branches:
      - main  # Change si ta branche principale est différente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, tokenizer
          tools: composer:v2

      - name: Installer les dépendances Laravel
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Créer le fichier .env
        run: |
          echo "${{ secrets.ENV_FILE }}" | tr -d '\r' > .env

      - name: Vérifier si .env existe
        run: |
          if [ ! -f .env ]; then
            echo "Le fichier .env est manquant !"
            exit 1
          fi

      - name: Nettoyer Laravel avant le déploiement
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Déployer via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: sftp
          local-dir: "./"
          server-dir: "/www/rrset/"
          exclude: |
            **/.git*
            **/node_modules/*
            **/vendor/*
            .env
            storage/logs/*
            storage/framework/sessions/*
            storage/framework/views/*

