name: Déploiement Laravel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Cloner le dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      # 2. Configurer PHP (installation de PHP 8.2 et extensions nécessaires)
      - name: Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2

      # 3. Installer les dépendances PHP
      - name: Installer les dépendances PHP
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 4. Créer le fichier .env à partir du secret GitHub
      - name: Créer le fichier .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # 5. Préparer les fichiers à déployer (exclure .git, node_modules et vendor)
      - name: Préparer les fichiers à déployer
        run: |
          mkdir deploy_temp
          rsync -av --progress --exclude '.git' --exclude 'node_modules' --exclude 'vendor' . deploy_temp/

      # 6. Déployer via SFTP avec sshpass
      - name: Déployer via SFTP
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          cd deploy_temp
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" sftp -o StrictHostKeyChecking=no -P 22 ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }} <<'EOF'

