name: Déploiement Laravel via SFTP

on:
  push:
    branches:
      - main  # Modifier si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      # 2️⃣ Configurer PHP
      - name: Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Modifier selon ton projet
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2

      # 3️⃣ Installer les dépendances PHP
      - name: Installer les dépendances PHP
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 4️⃣ Installer les dépendances Node.js
      - name: Installer les dépendances Node.js
        run: npm install && npm run build

      # 5️⃣ Créer le fichier .env à partir du secret GitHub
      - name: Créer le fichier .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # 6️⃣ Archiver les fichiers pour éviter les erreurs
      - name: Archiver le projet
        run: |
          mkdir deploy_temp
          rsync -av --progress --exclude=node_modules --exclude=vendor ./ deploy_temp/
          tar --warning=no-file-changed -czf project.tar.gz -C deploy_temp .

      # 7️⃣ Déployer via SFTP
      - name: Déployer via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: sftp
          local-dir: ./
          server-dir: /www/ton_projet/  # Modifier selon ton hébergeur
