name: Déploiement Laravel via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      # 2️⃣ Configurer PHP
      - name: Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2

      # 3️⃣ Installer les dépendances PHP
      - name: Installer les dépendances PHP
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 4️⃣ Créer le fichier .env à partir du secret GitHub
      - name: Créer le fichier .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # 5️⃣ Déployer via SFTP en transférant les fichiers
      - name: Déployer via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22  # Vérifie si ton hébergeur utilise un port différent
          source: "."
          target: "/www/ton_projet/"
          strip_components: 1
          overwrite: true

      # 6️⃣ Rafraîchir le cache Laravel sur le serveur
      - name: Rafraîchir le cache Laravel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            cd /www/rrset
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
