name: Déploiement Laravel via SFTP (mise à jour rapide)

on:
  push:
    branches:
      - main  # Déclenche le workflow seulement sur `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le dépôt
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      # 2️⃣ Configurer PHP
      - name: Configurer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2

      # 3️⃣ Installer les dépendances PHP sans `node_modules`
      - name: Installer les dépendances PHP
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      # 4️⃣ Créer le fichier .env à partir du secret GitHub
      - name: Créer le fichier .env
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # 5️⃣ Synchroniser uniquement les fichiers modifiés via SFTP
      - name: Déployer via SFTP (fichiers modifiés uniquement)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: sftp
          local-dir: ./
          server-dir: /www/ton_projet/  # Modifier selon ton hébergeur
          exclude: |
            node_modules/
            storage/
            vendor/
            .git/
            .github/
            tests/
            .env
            .gitignore
            README.md

      # 6️⃣ Nettoyer et mettre en cache Laravel sur le serveur
      - name: Rafraîchir le cache Laravel sur le serveur
        run: |
          curl --silent --show-error --fail --request POST \
          --url https://www.ton-domaine.com/artisan \
          --data "command=config:clear"
          curl --silent --show-error --fail --request POST \
          --url https://www.ton-domaine.com/artisan \
          --data "command=cache:clear"
          curl --silent --show-error --fail --request POST \
          --url https://www.ton-domaine.com/artisan \
          --data "command=config:cache"
