name: Deploy Laravel App via SFTP

on:
  push:
    branches:
      - main  # Change si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, tokenizer
          tools: composer:v2

      - name: Installer les dépendances Laravel
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Créer le fichier .env
        run: |
          echo "${{ secrets.ENV_FILE }}" | tr -d '\r' > .env

      - name: Vérifier si .env existe
        run: |
          if [ ! -f .env ]; then
            echo "Le fichier .env est manquant !"
            exit 1
          fi

      - name: Archiver le projet (exclure node_modules et vendor)
        run: tar --exclude='./node_modules' --exclude='./vendor' -czf project.tar.gz .

      - name: Déployer via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "project.tar.gz"
          target: "/www/rrset/"
          strip_components: 1
          overwrite: true
          rm: true

      - name: Décompression du projet sur le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            cd /www/rrset/
            tar -xzf project.tar.gz
            rm project.tar.gz
